### ISSUE TITLE
error running main

### ISSUE THREAD

**Issue by gusmagadc** [Yoyolick/ClashRoyaleAI#2]
Traceback (most recent call last):
  File ... , line 84, in <module>
    with open("tesseractPath.txt", "r") as tessPath:
FileNotFoundError: [Errno 2] No such file or directory: 'tesseractPath.txt'

**Comment by zoogies** [comment]
Looks like you figured it out as you closed the issue, but the tesseractpath.txt file should contain the path on your computer to your Tesseract.exe that came with the install. Let me know if you need any other help as this isn't documented well :)
